# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Img(object):
    def setupUi(self, Widget):
        Widget.setObjectName("child")
        Widget.resize(500, 500)
        self.label_image = QtWidgets.QLabel(Widget)
        self.label_image.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.label_image.setObjectName("label_image")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("child", "图片"))
        self.label_image.setText(_translate("child", "TextLabel"))



class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(560, 660)
        self.setFixedSize(self.geometry().size())  # 设置窗口不可改变大小
        self.match = QtWidgets.QPushButton(Widget)
        self.match.setGeometry(QtCore.QRect(280, 570, 101, 81))
        self.match.setObjectName("match")
        self.groupBox_distence = QtWidgets.QGroupBox(Widget)
        self.groupBox_distence.setGeometry(QtCore.QRect(390, 560, 161, 91))
        self.groupBox_distence.setObjectName("groupBox_distence")
        self.chi_square = QtWidgets.QRadioButton(self.groupBox_distence)
        self.chi_square.setEnabled(True)
        self.chi_square.setGeometry(QtCore.QRect(10, 30, 51, 29))
        self.chi_square.setChecked(True)
        self.chi_square.setObjectName("chi_square")
        self.euclidean = QtWidgets.QRadioButton(self.groupBox_distence)
        self.euclidean.setGeometry(QtCore.QRect(90, 30, 121, 29))
        self.euclidean.setObjectName("euclidean")
        self.cos = QtWidgets.QRadioButton(self.groupBox_distence)
        self.cos.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.cos.setObjectName("cos")
        self.groupBox_image = QtWidgets.QGroupBox(Widget)
        self.groupBox_image.setGeometry(QtCore.QRect(10, 10, 261, 641))
        self.groupBox_image.setObjectName("groupBox_image")
        self.image_list = QtWidgets.QListWidget(self.groupBox_image)
        self.image_list.setGeometry(QtCore.QRect(0, 20, 261, 621))
        self.image_list.setObjectName("image_list")
        self.groupBox_answer = QtWidgets.QGroupBox(Widget)
        self.groupBox_answer.setGeometry(QtCore.QRect(280, 290, 271, 271))
        self.groupBox_answer.setObjectName("groupBox_answer")
        self.list_answer = QtWidgets.QListWidget(self.groupBox_answer)
        self.list_answer.setGeometry(QtCore.QRect(0, 20, 271, 251))
        self.list_answer.setObjectName("list_answer")
        self.groupBox_match = QtWidgets.QGroupBox(Widget)
        self.groupBox_match.setGeometry(QtCore.QRect(280, 10, 271, 271))
        self.groupBox_match.setObjectName("groupBox_match")
        self.image_matched = QtWidgets.QGraphicsView(self.groupBox_match)
        self.image_matched.setGeometry(QtCore.QRect(0, 20, 271, 251))
        self.image_matched.setObjectName("image_matched")
        self.actionfileopen = QtWidgets.QAction(Widget)
        self.actionfileopen.setObjectName("actionfileopen")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "图片相似度匹配工具"))
        self.match.setText(_translate("Widget", "匹配"))
        self.groupBox_distence.setTitle(_translate("Widget", "距离衡量算法："))
        self.chi_square.setText(_translate("Widget", "卡方"))
        self.euclidean.setText(_translate("Widget", "欧氏"))
        self.cos.setText(_translate("Widget", "夹角余弦"))
        self.groupBox_image.setTitle(_translate("Widget", "匹配库图片"))
        self.groupBox_answer.setTitle(_translate("Widget", "匹配结果"))
        self.groupBox_match.setTitle(_translate("Widget", "样本图片"))
